apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: go-uname-k8s
    docker:
      dockerfilePath: Dockerfile
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
    - tools/skaffold/*.yaml
