apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-uname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: go-uname-k8s
